# Generated by Django 4.2 on 2026-01-09 17:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(help_text='Насколько книга подходит под запрос (0-1)', verbose_name='Оценка релевантности')),
                ('match_reasons', models.JSONField(default=list, help_text='Список причин, почему книга была рекомендована', verbose_name='Причины рекомендации')),
                ('is_shown', models.BooleanField(default=False, verbose_name='Показана пользователю')),
                ('is_clicked', models.BooleanField(default=False, verbose_name='Нажата пользователем')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время нажатия')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Рекомендация книги',
                'verbose_name_plural': 'Рекомендации книг',
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_level', models.CharField(choices=[('low', 'Низкий (устал)'), ('medium', 'Средний'), ('high', 'Высокий (полон сил)')], max_length=20, verbose_name='Уровень энергии')),
                ('current_mood', models.CharField(blank=True, max_length=200, verbose_name='Текущее настроение')),
                ('time_available', models.IntegerField(choices=[(15, '15 минут'), (30, '30 минут'), (60, '1 час'), (90, '1.5 часа'), (120, '2+ часа')], verbose_name='Доступное время')),
                ('desired_mood_after', models.CharField(help_text='Какое настроение хочется получить после чтения?', max_length=200, verbose_name='Желаемое состояние после чтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('recommended_books', models.ManyToManyField(related_name='recommended_in_sessions', through='users.BookRecommendation', to='books.book', verbose_name='Рекомендованные книги')),
                ('selected_mood_tags', models.ManyToManyField(blank=True, to='books.moodtag', verbose_name='Выбранные теги настроений')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия чтения',
                'verbose_name_plural': 'Сессии чтения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='Основной', max_length=100, verbose_name='Название профиля')),
                ('preferred_reading_time', models.IntegerField(default=30, help_text='Сколько минут обычно уходит на одну сессию чтения', verbose_name='Предпочитаемое время чтения (мин)')),
                ('preferred_complexity', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Предпочитаемая сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('favorite_mood_tags', models.ManyToManyField(blank=True, related_name='favored_by_profiles', to='books.moodtag', verbose_name='Любимые теги настроений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Читательский профиль',
                'verbose_name_plural': 'Читательские профили',
            },
        ),
        migrations.AddField(
            model_name='bookrecommendation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.readingsession', verbose_name='Сессия'),
        ),
        migrations.AlterUniqueTogether(
            name='bookrecommendation',
            unique_together={('session', 'book')},
        ),
    ]
