# Generated by Django 4.2 on 2026-01-09 17:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('mood_type', models.CharField(choices=[('energy', 'Энергия'), ('emotion', 'Эмоция'), ('situation', 'Ситуация'), ('goal', 'Цель')], default='emotion', max_length=20, verbose_name='Тип настроения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('emoji', models.CharField(blank=True, max_length=5, verbose_name='Эмодзи')),
            ],
            options={
                'verbose_name': 'Тег настроения',
                'verbose_name_plural': 'Теги настроений',
                'ordering': ['mood_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название книги')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('isbn', models.CharField(blank=True, max_length=20, unique=True, verbose_name='ISBN')),
                ('description', models.TextField(verbose_name='Описание')),
                ('pace', models.IntegerField(help_text='1 - очень медленный/сложный, 5 - очень быстрый/легкий', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Темп чтения')),
                ('complexity', models.IntegerField(help_text='1 - очень простая, 5 - очень сложная', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность')),
                ('emotional_intensity', models.IntegerField(default=3, help_text='1 - спокойная, 5 - очень эмоциональная', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Эмоциональная насыщенность')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Обложка')),
                ('cover_url', models.URLField(blank=True, verbose_name='Ссылка на обложку')),
                ('google_books_id', models.CharField(blank=True, max_length=50, verbose_name='ID Google Books')),
                ('published_date', models.CharField(blank=True, max_length=20, verbose_name='Дата публикации')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Издательство')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('average_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('ratings_count', models.IntegerField(default=0, verbose_name='Количество оценок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.genre', verbose_name='Жанр')),
                ('mood_tags', models.ManyToManyField(related_name='books', to='books.moodtag', verbose_name='Теги настроения')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserBookInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Просмотр'), ('save', 'Сохранение'), ('read', 'Прочитано'), ('like', 'Понравилось'), ('dislike', 'Не понравилось')], max_length=20, verbose_name='Тип взаимодействия')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата взаимодействия')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взаимодействие пользователя',
                'verbose_name_plural': 'Взаимодействия пользователей',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book', 'interaction_type')},
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['pace', 'complexity'], name='books_book_pace_788986_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='books_book_author_b941fe_idx'),
        ),
    ]
