# Generated by Django 4.2.11 on 2026-01-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('mood', models.CharField(choices=[('happy', 'Веселое'), ('sad', 'Грустное'), ('inspiring', 'Вдохновляющее'), ('calm', 'Спокойное'), ('adventurous', 'Приключенческое'), ('romantic', 'Романтическое')], max_length=50, verbose_name='Настроение')),
                ('complexity', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], max_length=50, verbose_name='Сложность')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
