# Generated by Django 4.2.11 on 2026-01-19 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mood',
            field=models.CharField(choices=[('happy', 'Веселое'), ('sad', 'Грустное'), ('inspiring', 'Вдохновляющее'), ('calm', 'Спокойное'), ('adventurous', 'Приключенческое'), ('romantic', 'Романтическое'), ('mysterious', 'Таинственное'), ('thoughtful', 'Задумчивое')], max_length=50, verbose_name='Настроение'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.CharField(blank=True, max_length=200, verbose_name='Любимые жанры')),
                ('reading_speed', models.CharField(choices=[('slow', 'Медленно'), ('medium', 'Средне'), ('fast', 'Быстро')], default='medium', max_length=20, verbose_name='Скорость чтения')),
                ('favorite_books', models.ManyToManyField(blank=True, to='books.book', verbose_name='Избранные книги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='BookSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_mood', models.CharField(choices=[('happy', 'Веселое'), ('sad', 'Грустное'), ('inspiring', 'Вдохновляющее'), ('calm', 'Спокойное'), ('adventurous', 'Приключенческое'), ('romantic', 'Романтическое'), ('mysterious', 'Таинственное'), ('thoughtful', 'Задумчивое')], max_length=50, verbose_name='Выбранное настроение')),
                ('selected_complexity', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], max_length=50, verbose_name='Выбранная сложность')),
                ('selected_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подбора')),
                ('recommended_books', models.ManyToManyField(to='books.book', verbose_name='Рекомендованные книги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подборка книг',
                'verbose_name_plural': 'Подборки книг',
                'ordering': ['-selected_date'],
            },
        ),
    ]
